# Generated by Django 5.1.7 on 2025-03-10 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('player_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('rep', models.CharField(max_length=100)),
                ('match_win', models.IntegerField()),
                ('match_total', models.IntegerField()),
                ('tomic_level', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('match_id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateField(auto_now=True)),
                ('score_1', models.IntegerField()),
                ('score_2', models.IntegerField()),
                ('attacker_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='g2', to='myapp.player')),
                ('attacker_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='g4', to='myapp.player')),
                ('goolkeeper_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='g1', to='myapp.player')),
                ('goolkeeper_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='g3', to='myapp.player')),
            ],
        ),
    ]
