# Generated by Django 5.1.7 on 2025-03-10 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_player_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='attacker_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='g2', to='myapp.player'),
        ),
        migrations.AlterField(
            model_name='match',
            name='attacker_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='g4', to='myapp.player'),
        ),
        migrations.AlterField(
            model_name='match',
            name='goolkeeper_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='g1', to='myapp.player'),
        ),
        migrations.AlterField(
            model_name='match',
            name='goolkeeper_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='g3', to='myapp.player'),
        ),
    ]
