# Generated by Django 5.1.7 on 2025-03-11 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_match_attacker_1_alter_match_attacker_2_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TodoItem',
        ),
    ]
