# Generated by Django 5.1.7 on 2025-03-11 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_delete_todoitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='attacker_1',
            new_name='team1_attacker',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='goolkeeper_1',
            new_name='team1_goalkeeper',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='score_1',
            new_name='team1_goals',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='attacker_2',
            new_name='team2_attacker',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='goolkeeper_2',
            new_name='team2_goalkeeper',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='score_2',
            new_name='team2_goals',
        ),
    ]
